#!/usr/bin/env python
import cmdproc
import mydbus

# https://developer.pidgin.im/wiki/DbusHowto
# provide asynchronous 
import gobject
import argparse

import logging

import logconfig
logger = logging.getLogger(__name__)

class ClementineCmdProc(cmdproc.CmdProc):
    config = {
        'program': 'clementine',
        'commands': [ 
            [['cmd', 'PLAY']],
            [['cmd', 'PAUSE']],
            [['cmd', 'VOLUME'], ['arg', 'int']],
        ],
    }
    def __init__(self, cmdserver_server, cmdserver_port):
        cmd_to_handler = {
            "PLAY": self.cmd_play,
            "PAUSE": self.cmd_pause,
            "VOLUME": self.cmd_volume,
            "NEXT": self.cmd_next,
            "PREVIOUS": self.cmd_previous,
        }
        super(ClementineCmdProc, self).__init__(cmdserver_server, cmdserver_port, cmd_to_handler=cmd_to_handler)

    def start(self):
        logger.info("Starting Clementine command processor...")
        self.connect()
        self.receive_and_dispatch_loop()

    def cmd_play(self, args):
        return mydbus.send_dbus('org.mpris.clementine', '/Player', 'org.freedesktop.MediaPlayer.Play')

    def cmd_pause(self, args):
        return mydbus.send_dbus('org.mpris.clementine', '/Player', 'org.freedesktop.MediaPlayer.Pause')

    def cmd_next(self, args):
        return mydbus.send_dbus('org.mpris.clementine', '/Player', 'org.freedesktop.MediaPlayer.Next')

    def cmd_previous(self, args):
        return mydbus.send_dbus('org.mpris.clementine', '/Player', 'org.freedesktop.MediaPlayer.Previous')

    def cmd_volume(self, args):
        cmd, level = args
        return mydbus.send_dbus('org.mpris.clementine', '/Player', 'org.freedesktop.MediaPlayer.VolumeSet', [level[1]])

def receive_msg(account, sender, message, conversation, flags):
    global _last_sender
    logger.info("DBUS: %s said: \"%s\", old _last_sender == %s", sender, message, _last_sender.value)
    # _state_lock.acquire()
    _last_sender.value = sender
    # _state_lock.release()

def main():
    parser = argparse.ArgumentParser(description="A clementine command processor.")
    args, processor = cmdproc.cmdproc_main(ClementineCmdProc, parser)
    processor.start()
        
if __name__ == '__main__':
    main()
